json.like_count @like_count
json.follow_count @follow_count
json.respond_count @respond_count
json.message_count @message_count
json.new_like @new_like
json.new_follow @new_follow
json.new_respond @new_respond
json.new_message @new_message
json.new_discover @new_discover